$(document).on("pagecreate","#mainpage",function(){
  $("#mainpage").on("click",function(){
    window.location.href="#cpanelpage";
  });    
});
$(document).on("pagecreate","#cpanelpage",function(){
  $(".icon-1").on("click",function(e){
	  e.preventDefault();
    alert('1');
  });    
  $(".icon-2").on("click",function(e){
	  e.preventDefault();
    alert('2');
  });    
  $(".icon-3").on("click",function(e){
	  e.preventDefault();
    alert('3');
  });    
});